name: Final Feed Publish

on:
  schedule:
    - cron: '0 18 * * *'  # 12:00 AM BD time (18:00 UTC)
  workflow_dispatch:

jobs:
  publish-final:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          pip install feedparser sentence-transformers scikit-learn

      - name: Run Final Feed Script
        run: python final_feed.py

      - name: Commit and Push Final XML
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add final.xml last_seen_final.json
          git commit -m "Publish final feed $(date)" || echo "No changes"
          git push
