name: Setup Python with Cache
on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: '3.11'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ inputs.python-version }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Cache shared Python dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            /opt/hostedtoolcache/Python/${{ inputs.python-version }}*/x64/lib/python${{ inputs.python-version }}/site-packages
          key: ${{ runner.os }}-py${{ inputs.python-version }}-common-${{ hashFiles('**/requirements.txt') }}-v1
          restore-keys: |
            ${{ runner.os }}-py${{ inputs.python-version }}-common-
