name: Hourly Collection (Stage 1)

on:
  schedule:
    - cron: '45 * * * *'  # Every hour at :45 UTC
  workflow_dispatch:

jobs:
  collect-temp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-temp-${{ hashFiles('**/requirements.txt') }}-v1
          restore-keys: |
            ${{ runner.os }}-pip-temp-
            ${{ runner.os }}-pip-

      - name: Cache Python site-packages (feedparser)
        uses: actions/cache@v4
        with:
          path: |
            /opt/hostedtoolcache/Python/3.11*/x64/lib/python3.11/site-packages
          key: ${{ runner.os }}-python-3.11-feedparser-${{ hashFiles('**/requirements.txt') }}-v1
          restore-keys: |
            ${{ runner.os }}-python-3.11-feedparser-
            ${{ runner.os }}-python-3.11-packages-

      - name: Install Dependencies
        run: |
          pip install --no-cache-dir feedparser

      - name: Run Hourly Collection
        run: python temp_feed.py

      - name: Commit and Push Updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Ensure files exist
          touch temp.xml last_seen_temp.json
          
          git add temp.xml last_seen_temp.json
          
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "📡 Hourly collection: $(date -u +"%Y-%m-%d %H:%M UTC")"
            git push
          fi
